name: Index posts
on:
  push:
    branches: [master]

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Run indexer
        run: node _indexer.mjs
      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Update posts indexes
          commit-message: Update posts indexes
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: actions/update-indexes
